apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        run: |-
          echo "hello world"
          sleep 10
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
