name: Test My Go Action-02

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Deploy
        run: echo "Deploying"
 
      - name: Test
        run: echo "Testing"
        
